modulo_home/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from modulo_home.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'home/', index, name='home'),
    url(r'home/newtask', new_task, name='new-task'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto_easytodo/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from modulo_home.views import *
from django.conf import settings
from django.conf.urls.static import static

import modulo_home.urls

urlpatterns = [
	url(r'', include(modulo_home.urls)),
    url(r'^admin/', admin.site.urls, name='admin'),
    # path('home/change-background', change_background),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modulo_home/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class TodoItem(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField(blank=True)
    category = models.ForeignKey(Category, default=1, on_delete=models.PROTECT)
    created = models.DateField(default=timezone.now().strftime("%Y-%m-%d"))
    due_date = models.DateField(default=timezone.now().strftime("%Y-%m-%d"))

    

class BackgroundFile(models.Model):
    img_path = models.ImageField(upload_to='background_img', blank=True)

modulo_home/forms.py
from django import forms
from .models import *
import datetime
from dateutil.relativedelta import relativedelta

class ConfigForm(forms.Form):
    img = forms.ImageField(required=False)
    newcategory = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Type a new category name'}), required=False)
    deletes = forms.CharField(widget=forms.TextInput(), required=False)

class NewTaskForm(forms.Form):
	title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'What do you have to do?'}))
	category = forms.ModelChoiceField(queryset=Category.objects.all(),
												widget=forms.Select(attrs={'class': 'form-control'}))
	due_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'class': 'form-control'}))

	def __init__(self, *args, **kwargs):
		super(NewTaskForm, self).__init__(*args, **kwargs)

		today = datetime.datetime.now()
		date = today + relativedelta(days=1)
		self.fields['due_date'].initial = date.strftime('%Y-%m-%d')
	

modulo_home/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
	context = {}
	background = BackgroundFile.objects.all().first()
	todos = TodoItem.objects.all()

	if request.method == 'POST':
		if 'changeSettings' in request.POST:
			form = ConfigForm(request.POST, request.FILES)
			if form.is_valid():
				print('form valido')
				img = form.cleaned_data.get("img")
				print(type(img))
				category = form.cleaned_data.get("newcategory")
				deletes = form.cleaned_data.get("deletes").split(",")
				print(deletes)
				if category != '':
					cat = Category()
					cat.name = category
					cat.save()
				if img != None:					
					background.img_path = img
					background.save()
				if len(deletes) > 1:
					print('deletes para deletar')
					for cat_id in deletes:
						print(cat_id)
						try:
							cat = Category.objects.get(pk=cat_id)
							cat.delete()
						except:
							pass


		if 'newTask' in request.POST:
			form = NewTaskForm(request.POST)
			if form.is_valid():
				print('newTask')
				content = form.cleaned_data["title"]
				category = form.cleaned_data["category"]	
				due_date = form.cleaned_data["due_date"]
				todo = TodoItem()
				todo.content = content
				todo.category = category
				todo.due_date = due_date
				todo.save()

		if 'deleteTasks' in request.POST:
			checkedlist = request.POST.getlist("checkedbox")
			for todo_id in checkedlist:
				task = TodoItem.objects.get(pk=int(todo_id))
				task.delete()

		return redirect(index)
	else:
		request.method = 'GET'
		context['back'] = background.img_path.url
		context['form_config'] = ConfigForm()
		context['form_newtask'] = NewTaskForm()
		context['todos'] = todos
		context['categories'] = Category.objects.all()
		return render(request, "index.html", context)

def new_task(request):
	context = {}
	background = BackgroundFile.objects.get(pk=1)

	if request.method == 'POST':
		form = NewTaskForm(request.POST, request.FILES) 
		if form.is_valid():
			print('form valido')
			img = form.cleaned_data.get("img")
			background.img_path = img
			background.save()

	context['back'] = background.img_path.url
	context['form_background'] = BackgroundForm()
	
	return render(request, "index.html", context)

projeto_easytodo/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index2.html', {})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">    
    <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
    <link href="{% static 'css/icheck-bootstrap.min.css' %}" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Lobster|Bitter&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    

    <link href="{% static 'css/bootstrap-datepicker.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

    <title>Easy ToDo</title>
</head>
    <body style="background-size: cover; background-repeat: repeat">
        <div class="container">
            <div class="row"> 
                <nav class="navbar col-lg-8 mx-auto" style="background-color: #CFD7C7;">
                    <div class="mx-auto order-0">
                        <a class="navbar-brand mx-auto" href="#"  style="font-family: Lobster; font-size: 30px; color: #0B2027">Easy ToDo <i class="fas fa-pen"></i></a>
                    </div>
                </nav>
            </div>
        </div>
    <div class="container">
        <div class="row">               
            {% block content %}
            {% endblock %}
            <!-- </div> -->
        </div>
    </div>

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

        <div id="body-content" class="rounded-bottom col-sm-12 col-lg-8 mx-auto p-4" style="background-color: #fff;">
                <h6 class="text-center" style="font-size: 15px; font-family: Bitter;">“Life is too complicated not to be orderly.” ~ Martha Stewart</h6>    
                <hr class="my-4">
                <form method="post" id="form_todolist">
                    {% csrf_token %}
                    {% for todo in todos %}
                    <div class="icheck-primary">
                        <input type="checkbox" class="taskCheckbox" name="checkedbox" id="{{ todo.id }}" value="{{ todo.id }}">
                        <label for="{{ todo.id }}"><span class="complete-">{{ todo.content }}</span></label>
                        <span class="badge badge-secondary">{{ todo.category.name }}</span>
                        <div class="row">
                            <div class="ml-5">
                            <i class="far fa-calendar-alt"></i><small>&nbsp;{{ todo.due_date }}</small>
                            </div>
                        </div>
                        <hr class="my-4">
                    </div>
                    {% endfor %}                
                <div class="text-center">
                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#addTaskModal">Add Task</button>
                    <button type="submit" class="btn btn-danger" name="deleteTasks">Delete Tasks</button>
                </form>
                    <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#configModal"><i class="fa fa-cog"></i></button>        
                </div>
        </div>
    </div>

<!-- Modal -->
<div class="modal fade" id="configModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
        <button type="button" class="close" data-dismiss="modal"  onclick="close_input()" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" enctype='multipart/form-data' id="form_settings" >
            {% csrf_token %}
            <div class="row">
                <div class="col-4 col-md-3 col-lg-3"><label>Background:</label></div>
                <div class="col-8 col-md-9 col-lg-9">
                    <input type="file" name="img" accept="image/*" id="id_img" hidden="True" onchange="PreviewImage();">
                    <img onclick="document.getElementById('id_img').click(); return false;" id="uploadPreview" style="width: 100px; height: 100px;" />
                    <small class="text-muted form-text">Choose a file.</small>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-4 col-md-3 col-lg-3"><label>Categories:</label></div>
                <div class="col-8">
                        {% for cat in categories %}
                        <span class="badge badge-light" id="badge-{{ cat.id }}">{{ cat.name }}
                            <a href="" id="{{ cat.id }}" style="color: red;"><i class="fa fa-times fa-lg" aria-hidden="true"></i></a></span>
                        {% endfor %}
                        <br>
                        <a href="" onclick="return new_category()" id="plus"><i class="fas fa-plus-circle"></i></a>
                        {{ form_config.newcategory }}
                </div>
                {{ form_config.deletes }}
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"  onclick="close_input()">Close</button>
        <button type="submit" class="btn btn-success" name="changeSettings">Save changes</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addTaskModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add New Task</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" enctype='multipart/form-data' id="form_new_task" >
            {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    Description:
                </div>
                <div class="col-12">
                    {{ form_newtask.title }}
                </div>
                <div class="col-12">
                    Category:
                </div>
                <div class="col-12">
                    {{ form_newtask.category }}
                </div>
                <div class="col-12">
                    Due Date: {{ form_newtask.due_date }}
                </div>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success" name="newTask">Save changes</button>
        </form>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $( function() {
        $( "#id_due_date" ).datepicker({
            format: 'yyyy-mm-dd',
        });
    });

    function new_category(){
        $('#plus').hide();
        $('#id_newcategory').show();
        return false;
    }
    function close_input(){
        console.log('close');
        $('#id_newcategory').hide()
        $('#plus').show();
    }

    $(document).ready(function(){
        $('#id_newcategory').hide();
        $('#id_deletes').hide();

        background_path = '{{ back|safe }}';

        $('body').css('background-image', 'url(' + background_path + ')');

        var bg_img = $("body").css("background-image");
        bg = bg_img.replace('url(','').replace(')','').replace(/\"/gi, "");
        var box_img = $("#uploadPreview");
        $(box_img).attr("src", bg);

        $('.js-example-basic-multiple').select2();
    });

    function PreviewImage() {
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("id_img").files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById("uploadPreview").src = oFREvent.target.result;
        };
    };

</script>   

{% for cat in categories%}
<script type="text/javascript">    
    $('#badge-{{ cat.id }}').click(function(){
        $(this).hide();
        var old_value = $("#id_deletes").val();
        console.log('-->', $("#id_deletes"));
        var id = '{{ cat.id }},'
        console.log(id);
        new_value = old_value.concat(id);
        $("#id_deletes").val(new_value);
        console.log('{{ cat.id }}');
        console.log($("#id_deletes").val());
        return false;
    });
</script>
{% endfor %}
{% endblock %}